### ISSUE TITLE
Misleading user agent result

### ISSUE THREAD

**Issue by rio2311** [HaraldWalker/user-agent-utils#84]
While using latest version of browser Dolphin for Android on Samsung galaxy S3, I got result Mobile Safari, platform Andoid.

I see, there is nothing to identify browser as Dolphin, but could you at least not use Safari in this case as a result? It is very misleading and confusing for user. Thank you!

User-Agent string is:
Mozilla/5.0 (Linux; U; Android 4.1.2; en-ca; SGH-I747M Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

Browser Used: Latest Doplphin version;
Result: Mobile Safari, Platform: Android 4.x

**Comment by HaraldWalker** [comment]
Until now Dolphin used dolphin in the user agent, so it was detectable. If they send a user agent that looks like Mobile Safari there nothing I can do about it. Complain at http://dolphin.com. They probably do that so that they are getting exactly the same response as mobile safari if websites user the user agent to render different results.
